default: true

MD013:
  # Number of characters
  line_length: 100
  # Number of characters for headings
  heading_line_length: 100
  # Number of characters for code blocks
  code_block_line_length: 100
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD046/code-block-style - Code block style
MD046: false
